name: reftcl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bidict==0.23.1
      - bleach==6.2.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - clarabel==0.11.1
      - click==8.2.1
      - comm==0.2.2
      - contourpy==1.3.2
      - cvxpy==1.7.1
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==3.0.1
      - debugpy==1.8.15
      - decorator==5.2.1
      - deepspeed==0.17.4
      - defusedxml==0.7.1
      - diffusers==0.34.0
      - dill==0.3.5.1
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - evaluate==0.4.5
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.5
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.2.0
      - fuzzywuzzy==0.18.0
      - gcsfs==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.2.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - htmlmin==0.1.12
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - idna==3.10
      - imagehash==4.3.1
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - ipykernel==6.30.0
      - ipython==8.14.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - k-means-constrained==0.7.3
      - kiwisolver==1.4.8
      - lark==1.2.2
      - levenshtein==0.27.1
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mizani==0.14.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.3
      - multimethod==1.12
      - multiprocess==0.70.13
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1
      - nltk==3.8.1
      - nnsight==0.4.11
      - notebook==7.4.4
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - ortools==9.9.3963
      - osqp==1.0.4
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - phik==0.12.5
      - pickleshare==0.7.5
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotnine==0.15.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - puremagic==1.30
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pyreft==0.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-json-logger==3.3.0
      - python-levenshtein==0.27.1
      - python-socketio==5.13.0
      - pytz==2025.2
      - pyvene==0.1.8
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - qpth==0.0.18
      - quadprog==0.1.13
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.26.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.4.2
      - scipy==1.15.3
      - scs==3.2.8
      - seaborn==0.12.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.1
      - setproctitle==1.3.6
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.1
      - torchvision==0.22.1
      - tornado==6.5.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.55.2
      - triton==3.3.1
      - typeguard==4.4.4
      - types-python-dateutil==2.9.0.20250708
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - visions==0.8.1
      - wandb==0.17.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wordcloud==1.9.4
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - ydata-profiling==4.16.1
      - zipp==3.23.0
